
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/sysinventory?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 888888
#      filters: stat,wall,log4j
      filters: stat,wall
      min-idle: 10
      initial-size: 5
      max-active: 100
      max-wait: 200
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 0
#        max-wait: -1
#        max-idle: 10
#    timeout: 5000
